### PR TITLE
Add the ability to encode an object using the supported formats

### PR DESCRIPTION
**Pull request by adamvoss**
This adds a new function `encode` that takes the object to be encoded and the specified format and returns a promise that will resolve to the the object stringified in the specified format.

This only adds support at the API level, the functionality is not exposed to the command line app.
This does not add support for any of the tabular formats (csv, xls, xlsx).  The Excel formats will take some additional effort in learning the API.  Depending on how nested objects are handled with them, the desired behavior for the CSV implementation may change, so it was withheld.

### CODE REVIEW

**Comment by laktak** [comment]
Thanks for your PR! 

I'll try to take a look at this soon.

**Comment by adamvoss** [comment]
I'd ask you hold hold off for a little bit.  I am working on some major changes.  When that is done, we can discuss if it is worth trying to restore backwards compatibility in my fork, releasing a new major version of any-json, or if I should just start a new project out of my fork.

**Comment by laktak** [comment]
OK. Just let me know.

**Comment by adamvoss** [comment]
Closed in favor of #5

**Pull request closed without merging**
